la var end01	"1. Out of Stock of Any Vaccine at Time of Survey"
la var end01a	"1a. Out of Stock of Vaccine Janssen at Time of Survey"
la var end01b	"1b. Out of Stock of Vaccine AstraZeneca at Time of Survey"
la var end01c	"1c. Out of Stock of Vaccine Pfizer at Time of Survey"
la var end01d	"1d. Out of Stock of Pentavalent (DTC/Hepatitis B/Hib) at Time of Survey"
la var end01e	"1e. Out of Stock of Vaccine Pollio Injectable (VPI) at Time of Survey"
la var end01f	"1f. Out of Stock of Vaccine Pollio Oral (VPO) at Time of Survey"
la var end01g	"1g. Out of Stock of Vaccine Rotarix at Time of Survey"
la var end01h	"1h. Out of Stock of Vaccine Anti Rougeoleux (VAR) at Time of Survey"
la var end01i	"1i. Out of Stock of Vaccine Anti Tetanique (VAT) at Time of Survey"
la var end01j	"1j. Out of Stock of Vaccine Anti Pneumococcique (PCV10) at Time of Survey"
la var end01k	"1k. Out of Stock of Vaccine BCG at Time of Survey"
la var end02 	"2. Out of Stock of Malaria Tests at Time of Survey"
la var end03 	"3. Out of Stock of Malaria Tests in the 3 Months Before Survey"
la var end04 	"4. Out of Stock of Antimalarial Medicine at Time of Survey"
la var end05	"5. Out of Stock of Any Contraceptive Method at Time of Survey"
la var end05a	"5a. Out of Stock of Implants at Time of Survey"
la var end05b	"5b. Out of Stock of Injectable Depo Provera at Time of Survey"
la var end05c	"5c. Out of Stock of Injectable Syana Press at Time of Survey"
la var end05d	"5d. Out of Stock of Pills at Time of Survey"
la var end05e	"5e. Out of Stock of Male Condoms at Time of Survey"
la var end06 	"6. Out of Stock of Any Contraceptive Method in the 3 Months Before Survey"
la var end07 	"7. Out of Stock of LARC Removal Supplies at Time of Survey"
la var end08 	"8. Out of Stock of LARC Removal Supplies in the 3 Months Before Survey"
la var end09	"9. CHW Out of Stock of Malaria Tests"
la var end10	"10. CHW Out of Stock of Malaria Treatment"
la var end11	"11. CHW Out of Stock of Any of the Four FP Methods"
la var end11a	"11a. CHW Out of Stock of Injectable Depo Provera"
la var end11b	"11b. CHW Out of Stock of Injectable Sayana Press"
la var end11c	"11c. CHW Out of Stock of Pills"
la var end11d	"11d. CHW Out of Stock of Male Condoms"
la var end12 	"12. Number of Providers Present Today"
la var end13 	"13. Rated Emergency Reordering Procedure Somewhat or Very Easy"
la var end14 	"14. Ordered Medical Commodities More Frequently Than Every 3 Months"
la var end15 	"15. Number of FP Visits Completed in Last Month (All Methods Combined)"
la var end16 	"16. Number of New Clients Receiving FP in the Last Month"
la var end17 	"17. Out of Stock Prevented Helping a Patient in the Last Six Months"
la var end18 	"18. In Past 6 Months Staff Traveled to District Pharmacy to Place Emergency Order"
la var end19 	"19. Facility Has Working Fridge for Cold Chain Storage"
la var end20 	"20. Provider is Absent"
la var end21 	"21. Informal Payment for Contraception"

la var end22 	"22. Never Encouraged Patient to Choose a Different Method Due to Method Stockouts"
la var end23	"23. Never Encouraged Patient to Use Method Other Than the One Wanted"
la var end24	"24. Never Encouraged Patient to Use Long-Acting Method"
la var end25	"25. Never Encouraged Patient to Use Short-Acting Method"
la var end26	"26. Never Encouraged Patient to Use Permanent Method"
la var end27	"27. Never Encouraged Patient to Use Natural Method"
la var end28	"28. There are Frequent Out of Stocks of Needed Supplies/Commodities"
la var end29	"29. Patients Frequently Leave without their Preferred FP Method"
la var end30	"30. I Feel Like I Have Everything I Need to Provide the Best Care"
la var end31	"31. Provider Received Their Salary Within the Last Month"
la var end32 	"32. Provider is Satisfied or Very Satisfied Working Here"
la var end33	"33. Mean Number of Days Away from the Facility to Collect Supplies"
la var end34	"34. Currently Using Contraception"
la var end35	"35. Received Preferred Method"
la var end36	"36. Made an Informal Payment for FP"
la var end37a	"37a. Did the Nurses or Other Providers Introduce Themselves to You?"
la var end37b	"37b. Did the Nurses or Other Providers Call You By Your Name or Child's Name?"
la var end37c	"37c. Did You Feel the Nurses and Other Staff Treated You in a Friendly Manner?"
la var end37d	"37d. Did the Doctors, Nurses and Other Staff Show That They Cared About You?"
la var end37e	"37e. Did the Provider Ask You if You Had Any Questions?"
la var end37f	"37f. Did the Nurses at the Facility Talk to You About How You Were Feeling?"
la var end38	"38. Facility Did Not Have the Medicines and Supplies When You Visited"
la var end39	"39. Currently Using Any Contraceptive Method"
la var end40	"40. Currently Using a Modern Contraceptive Method"
la var end41	"41. Has Aligned and Preferred Contraceptive Use"
la var end42	"42. Has Unmet Need for Contraception"
la var end43	"43. Obtained Method from Public Facility"
la var end44	"44. Obtained Method from Closest Facility to Home"
la var end45	"45. Among Those Not Using, Wishes They Were Using Contraception"
la var end46	"46. Received MII+"
la var end47	"47. FP User Would Refer a Friend to the Facility"
la var end48	"48. Made an Informal Payment"
la var end49	"49. There is Another Method They Would Prefer to Use"
la var end50	"50. Among Users, Felt Had Enough Information to Make a Good Decision"
la var end51	"51. Among Users, Felt They Could Not Say No to Using"
la var end52	"52. Child Never Received a Vaccine to Prevent Disease"
la var end53	"53. Child Received BCG"
la var end54	"54. Child Received Pentavalent"
la var end55	"55. Child Received Pneumococcal"
la var end56	"56. Child Received Rotavirus"
la var end57	"57. Child Received Measles"
la var end58	"58. Among Children with Fever in Last Two Weeks, Pct Who Had Blood Taken"
la var end59	"59. Among Children with Fever in Last Two Weeks, Pct Diagnosed with Malaria"
la var end60	"60. Sought Healthcare from a Public or Private Facility, Ever"
la var end61	"61. Sought Healthcare from a Public Facility the Most Recent Time"
la var end62	"62. Strongly Agree Staff Was Friendly"
la var end63	"63. Strongly Agree Staff Gave All Information Needed"
la var end64	"64. Strongly Agree Staff Provided High Quality Services"
la var end65	"65. Strongly Agree Staff Ensured Privacy"
la var end66	"66. Strongly Agree Staff Involved Me in Decisions About My Care"
la var end67	"67. Disagree or Strongly Disagree I Had to Wait a Long Time to Receive Care"
la var end68	"68. Disagree or Strongly Disagree Staff Did Not Have Methods"
la var end69	"69. Disagree or Strongly Disagree Staff Did Not Have Vaccines"
la var end70	"70. Perceived High Quality Care at the Closest Facility"
la var end71	"71. Those Highly Satisfied with Care Among Those at Public Facility in Last Year"
la var end72	"72. Those Who Rated Care as Excellent Quality at Public Facility in Last Year"
la var end73	"73. Those Treated Very Well by Provider at Public Facility in Last Year"
la var end74	"74. Those Very Confident They Could Receive Method Next Week at Closest Facility"
la var end75	"75. Those Very Confident the Closest Facility Has a Reliable Supply of FP"
la var end76	"76. Those Very Confident in Receiving Vaccinations at the Closest Facility"
la var end77	"77. Obtained Last Method from Community Health Worker"
